// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolyEdgeScout.Infrastructure.Persistence;

#nullable disable

namespace PolyEdgeScout.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260323044932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PolyEdgeScout.Domain.Entities.AppStateEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppState", (string)null);
                });

            modelBuilder.Entity("PolyEdgeScout.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("PolyEdgeScout.Domain.Entities.Trade", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Edge")
                        .HasColumnType("REAL");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPaper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketQuestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("ModelProbability")
                        .HasColumnType("REAL");

                    b.Property<double>("Outlay")
                        .HasColumnType("REAL");

                    b.Property<double>("Shares")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TxHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("PolyEdgeScout.Domain.Entities.TradeResult", b =>
                {
                    b.Property<string>("TradeId")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("Fees")
                        .HasColumnType("REAL");

                    b.Property<double>("Gas")
                        .HasColumnType("REAL");

                    b.Property<double>("GrossProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("MarketQuestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("Roi")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("SettledAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Shares")
                        .HasColumnType("REAL");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("TradeId");

                    b.ToTable("TradeResults", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
